# Generated by Django 4.0.1 on 2022-07-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_player_country_alter_team_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='asking_price',
            field=models.IntegerField(default=0),
        ),
    ]
